### ISSUE TITLE
gcc/g++ verison

### ISSUE THREAD

**Issue by rlczddl** [Whu-wxy/Qt-libtorch#1]
Hi, what version of your gcc or g++(Mine is 7.5.0)? I test libtorch1.6.0、1.4.0 and 1.3.0, all must setting CONFIG += c++14 and QMAKE_CXXFLAGS += -D_GLIBCXX_USE_CXX11_ABI=0 in the qtcreator' pro file, but this setting is not compatible with other programs in my project.

**Comment by Whu-wxy** [comment]
gcc=5.4
Qt=5.13

**Comment by rlczddl** [comment]
Thanks. Have you encountered this situation in my updated message?

**Comment by Whu-wxy** [comment]
so you can compile a Qt code without libtorch and  libtorch without Qt？It's kind of weird.

**Comment by rlczddl** [comment]
Yes, it is because of  the setting of "CONFIG += c++14 and QMAKE_CXXFLAGS += -D_GLIBCXX_USE_CXX11_ABI=0" in qtcreator' pro file.

**Comment by rlczddl** [comment]
Finally i found the solution:we should download  libtorch-cxx11-abi-shared-with-deps-1xxx.zip, and  set CONFIG += c++14 and QMAKE_CXXFLAGS += -D_GLIBCXX_USE_CXX11_ABI=1. It is because of  the problem of std::string for old gcc version.

**Comment by Whu-wxy** [comment]
Congratulations, this's very helpful
